### ISSUE TITLE
Should the new squirrel app run after update finishes in clickonce app?

### ISSUE THREAD

**Issue by theofanis** [flagbug/ClickOnceToSquirrelMigrator#4]
I run await ```migrator.Execute()``` in my ClickOnce app and when this finishes, the new Squirrel app is executed. 

After looking through the migrator's code I see that silent install with true value is used with ```FullInstall```, so this shouldn't happen, especially after this https://github.com/Squirrel/Squirrel.Windows/pull/162.

Any info on this?

**Comment by flagbug** [comment]
Do you have the newest version of Squirrel.Windows installed?

I haven't pushed out a new version with the upgrade, but you can just do `Update-Package Squirrel.Windows` and it should work.

**Comment by theofanis** [comment]
You're right, thanks mate.

**Comment by flagbug** [comment]
:+1:
